  name: CICD - Frontend Only

  on:
    push:
      branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        # Checkout source code
        - name: Checkout source
          uses: actions/checkout@v3


      # List files to verify the directory structure
        - name: List files in the current directory
          run: ls -alh

        # List files in my-app folder to confirm it exists
        - name: List files in my-app folder
          run: ls -alh ./my-app

        # Build Frontend Docker Image
        - name: Build Frontend Docker Image
          run: |
            docker build -t kkwk1997/my-app:latest -f ./my-app/Dockerfile ./my-app

        # Login to Docker Hub
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

        # Push Frontend Docker Image
        - name: Push Frontend Docker Image
          run: docker push kkwk1997/my-app:latest

    deploy-frontend:
      needs: build
      runs-on: swe5006-frontend
      steps:
        # Pull Frontend Docker Image
        - name: Pull Frontend Docker Image
          run: |
            docker system prune -f
            docker pull kkwk1997/my-app:latest

        # Stop existing Frontend container
        - name: Stop existing Frontend container
          run: docker stop my-app-container || true

        # Remove existing Frontend container
        - name: Remove Frontend container
          run: docker rm my-app-container || true

        # Deploy Frontend container
        - name: Deploy Frontend
          run: docker run -d -p 80:3000 --name my-app-container kkwk1997/my-app:latest
